### ISSUE TITLE
@remotion/player package for embedding Remotion videos in websites

### ISSUE THREAD

**Issue by JonnyBurger** [JonnyBurger/remotion#133]

**Comment by pahund** [comment]
I'm trying to find out the minimum code for a player component that lets you preview embedded Remotion videos. Here's what I have so far:

* https://codesandbox.io/s/remotion-car-slideshow-001-fnpqh

Currently, it only works if you add `/car-slideshow` to the URL in the Sandox preview panel. This is because the `RemotionRoot` component sets the current composition by parsing the URL.

So the test URL for this sandbox is:

* https://fnpqh.csb.app/car-slideshow

@JonnyBurger How can I set the current composition? I've tried getting the `CompositionManager` instance from the context and using `setCurrentComposition` in my `useEffect` callback, but that didn't work.

**Comment by pahund** [comment]
> Currently, it only works if you add `/car-slideshow` to the URL in the Sandox preview panel. This is because the `RemotionRoot` component sets the current composition by parsing the URL.

✅ fixed it: https://codesandbox.io/s/remotion-car-slideshow-002-p2vzu

**Comment by JonnyBurger** [comment]
Wow, that's fire @pahund! Great proof of concept. I think this fits in well in the vision of Remotion that you can embed a video, customize it and then render it on the server. And looks like we are already closer than I thought!

I need to take care of some of the fundamentals like audio support and a few bugs that are on this tracker, but then I would love to tackle this and make the use case more streamlined, like by exporting the RemotionRoot, not needing the hacks, an official player, and docs.

Thanks a lot for sharing, this is a nice PoC that I will also share if someone attempts something similar.

**Comment by pahund** [comment]
Thanks for the kind feedback! Here is the latest version, that shows a slide show of car pictures:

https://codesandbox.io/s/remotion-car-slideshow-005-hx8w7

**Comment by pahund** [comment]
Btw. I've noticed you used `setTimeout` to time the animation frames in the preview player that's bundled. I think `requestAnimationFrame` would work better, no?

**Comment by yuta0801** [comment]
> Btw. I've noticed you used `setTimeout` to time the animation frames in the preview player that's bundled. I think `requestAnimationFrame` would work better, no?

I've also noticed that, and tried that here #148

**Comment by JonnyBurger** [comment]
Progressing well, thanks @Iamshankhadeep for pushing it!

Quick checklist of what we should implement:

- Events: ‘seeked’, ‘error’, ‘pause’, ‘play’
- getCurrentTime()
- should be able to press space to play / pause
- need to check accessibility / keyboard controls
- `loop` property
- `autoPlay` property
- `requestFullscreen?`
- Controls should hide themselves when leaving hover state
- Apply the following style to all children:
```
 * {
    box-sizing: border-box;
 }
```
