### ISSUE TITLE
FEATURE: adding `none` as `extrapolate` config for `interpolate`

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [JonnyBurger/remotion#145]
It would be good if we can chain several `interpolate` functions like:
```
const position= 
  interpolate(frame, [0, 10], [-200, 140], { extrapolateRight: "none" }) || 
  interpolate(frame, [90, 100], [140, -200], { extrapolateLeft: "none" }) || 100
```
For this to work, `interpolate` needs to return `undefined` for frames outside range specified.
This will allow us to make start/end transitions with much less complexity and code.

**Comment by JonnyBurger** [comment]
Thanks for bringing this up!

What would you think about supporting the following?:

```
const position = interpolate(frame, [0, 10, 90, 100], [-200, 140, 140, -200])
```

Because your method seems prone to someone acidentially introducing a bug: If you interpolate to 0, then it will fallback to the next interpolate function. Let me tweak your example: 

```
const position= 
  interpolate(frame, [0, 10], [-200, 200], { extrapolateRight: "none" }) || 
  interpolate(frame, [90, 100], [200, -200], { extrapolateLeft: "none" }) || 100
```

Now it will evaluate like this:

```
frame = 0     position = -200
frame = 1     position = -160
frame = 2     position = -120
frame = 3     position = -80
frame = 4     position = -40
frame = 5     position = 100 // easy to introduce BUG because 0 is a falsy value
frame = 6     position = 40
frame = 7     position = 80
...
```

You could use `??` expression to avoid it, but still can become tricky. But it's a good point, therefore I make a counterproposal :)

**Comment by Dragomir-Ivanov** [comment]
Well, it doesn't click for me :)
Also if you make it as your proposal, `extrapolate[Right/Left]` will be set for all ranges. And this might not be desired.

You are right about the `falsy` values, though. `??` is one good solution.

You have such a lovely API, will be shame to spoil it:) We can leave this issue for a while, maybe someone with better idea will pop up.

Thanks a ton!

**Comment by JonnyBurger** [comment]
@Dragomir-Ivanov 
It's the same type of interpolation that React Native / Reanimated also supports, it at least feels intuitive for me. Here is some explanation better than mine: https://reactnative.dev/docs/animations#interpolation

I am not against introducing your approach as well, it shouldn't make the API too confusing since you have to explicitly opt into it 👍

**Comment by Dragomir-Ivanov** [comment]
@JonnyBurger 
Oh, didn't knew about this. 
In this case, let's go with it, probably I am not as smart as those guys :)
