### ISSUE TITLE
Reanimated 2 support

### ISSUE THREAD

**Issue by Kiesco08** [JonnyBurger/remotion#155]
Since React Native web is supported, would it be doable to support the Reanimated 2 library in Remotion? I got to the point where the compiler complains because it is not able to detect the platform. I'm new at this and I'm not sure whether there is a limitation or if I'm missing something.

![Screen Shot 2021-03-01 at 8 43 39 AM](https://user-images.githubusercontent.com/2665475/109505079-3d63ba00-7a6a-11eb-8ff5-70993c7619e1.png)

**Comment by JonnyBurger** [comment]
Hey @Kiesco08!

It's probably not the best idea to want to use Reanimated 2 in Remotion, because the animations are not dependant on the frame number. Basically, Reanimated is a way to opt out of using React to do animations and to run them imperatively for performance reason in React Native.

Remotion however embraces doing animations by making a lot of rerenders. It's just a different usecase.
So Reanimated animations will probably not work as intended, but you can use the Remotion APIs `spring()` and `interpolate()` - as a Reanimated user you should feel right at home.

If you want to get Reanimated working nonetheless, you need to override the Webpack config of Remotion.
Reanimated requires a special Babel plugin and other React Native stuff needs to be polyfilled (flow code transpilationn, `__DEV__`, `.web.js` files).

We don't include this by default because it would be impossible to handle all the possible usecases which Webpack enables. Instead, we leave it up to you to override the webpack config and just add whatever you need.

I have created an example repository which uses the Webpack override function to install Reanimated 2 and make RN stuff work: https://github.com/JonnyBurger/remotion-react-native-webpack-config-demo
You can use it as a template.

Hope this helps! 😊

**Comment by Kiesco08** [comment]
Incredibly helpful! Thanks @JonnyBurger
