### ISSUE TITLE
Possible performance improvement: capture raw frames instead of PNG/JPEG?

### ISSUE THREAD

**Issue by mifi** [JonnyBurger/remotion#162]
First of all really awesome work on this! And really clean, functional code, I love it! I've been thinking about making a react video editor myself but I never got to it.

So I can see that it is rendering to JPEG/PNG before stitching the images together:

https://github.com/JonnyBurger/remotion/blob/3226ce10e15a2d3342518da6da98c52e80fb8007/packages/cli/src/render.tsx#L149

I may be wrong, but I think that this could be done faster by not going through JPEG/PNG but instead transfering the raw frames directly.
I actually have a similar project [editly](https://github.com/mifi/editly) which uses the raw frame method.

I create an ffmpeg process which reads RGBA frames from stdin:
https://github.com/mifi/editly/blob/03cb2d78815431a57cab82a62c65ea89538c9a95/index.js#L212

Then I write frame by frame to that stdin stream once the frames are ready:
https://github.com/mifi/editly/blob/03cb2d78815431a57cab82a62c65ea89538c9a95/index.js#L367

I'm not sure if puppeteer can capture as raw frame (rgba) though.
I can look more into this when I have some time but I'm happy to hear your thoughts.

**Comment by JonnyBurger** [comment]
Great idea! It sounds like it would improve the performance but the problem seems to be Puppeteer:

https://github.com/puppeteer/puppeteer/blob/v8.0.0/docs/api.md#pagescreenshotoptions

which only supports PNG and JPEG. So unfortunately I think there's nothing we can do to optimize even though it would be really awesome! 😌
Closing it but if you have ideas or think otherwise, comment and I'll reopen it :)
