### ISSUE TITLE
[Feature request]: Support Lottie export

### ISSUE THREAD

**Issue by ltcaosj** [JonnyBurger/remotion#175]
Hi Jonny,

It should be awesome if remotion can support exporting animation video to Lottie JSON.

Regards,
Long Cao

**Comment by JonnyBurger** [comment]
Hi Long Cao!

Thanks a lot for the featur e request, but after thinking about it a bit, I've came to the decision that I don't want to implement it, mostly because technically it's too hard to make it work well.

Lottie is completely vector based format and it's animations are just JSON files. Remotion tries to make video creation possible on a higher level - it supports almost all web technologies, and SVG/Vector is just a small part of it. I don't see a path forward on how to generically convert Remotion animations into Lottie files. It's unclear how this could be feasibly done and there is also no 'spec' of how Lottie files work as far as I know. With no plan of how this could be achieved, I'm going to close this issue. You are always welcome to request new features or feedback though!

**Comment by ltcaosj** [comment]
Thanks @JonnyBurger for your response. It's clear now :)
