### ISSUE TITLE
FFMPEG: simplify dependency

### ISSUE THREAD

**Issue by dy** [JonnyBurger/remotion#21]
Hey!
Just a couple of great libs that can come useful for rendering, instead of pretty shaky FFMPEG dependency from the docs.
* https://ffmpegwasm.github.io/
* https://github.com/mattdesl/mp4-h264

**Comment by avindra** [comment]
Shaky? [ffmpeg is widely available in various repos](https://repology.org/project/ffmpeg/versions). The WASM versions may present more problems actually (is multi-threading stable yet?)

**Comment by dy** [comment]
Ah, ok. Because docs link points to some internet-archived bundle https://github.com/adaptlearning/adapt_authoring/wiki/Installing-FFmpeg

**Comment by JonnyBurger** [comment]
This is worth considering. We could ship FFMPEG with Remotion, but then it should work on all platforms which is very hard to achieve. This is why right now it's an external dependency. If a universal binary can be shipped with Remotion, I am down for this.

MP4-H264 is also worth considering, I am keeping in mind though for later that I want to include Audio support and was hoping that FFMPEG can help with sequencing and composing the Audio files. I wouldn't wanna lose this functionality.

Advice and tips regarding this appreciated! Leaving this open for now.

**Comment by JonnyBurger** [comment]
I have currently no idea how this could be optimized:

- Other projects don't have all the options that FFMPEG has - we've built a heavy reliance on many different FFMPEG features by now.
- Shipping an FFMPEG binary with Remotion is hard, there are tons of different operating system / architecture combinations, I don't want to get into the business of providing binaries for all of those, it's a heavy effort.
- Running FFMPEG in the browser through WASM doesn't provide a benefit because we still need to screenshot using Puppeteer, so it's not possible to export the video just in the browser.

So I think the best way is to keep it as it is, have FFMPEG as a peer dependency. With no plans to implement it, I am going to close this issue.
