### ISSUE TITLE
Livestreaming

### ISSUE THREAD

**Issue by nicopace** [JonnyBurger/remotion#26]
It would be great if remotion would allow to stream the video produced in a live fashion.
That would allow to send it to a livestream platform (like peertube, twitch, youtube, etc), or integrate it into OBS Studio.

**Comment by JonnyBurger** [comment]
Good idea!

I'll leave this ticket open for future work. The biggest problem right now I think is that rendering Remotion videos is slower than real-time, it needs to become a lot faster.

How would you imagine this to work? How would you declaratively code a livestream?

**Comment by linkstrifer** [comment]
Maybe just stream the video editor without controls?

I don't see any use-case for the actual rendered video to be streamable

**Comment by JonnyBurger** [comment]
I am closing this issue because I think there is not a clear path forward and there has been little activity since the issue has opened.

It's unclear what the feature would actually do - similar to how iMovie. Premiere etc. don't support livestreaming either because they are linear editors where the video gets created on a timeline and then exported.

Livestreaming tools like OBS work fundamentally differently, where some live input sources are taken, e.g. Webcam, Screen Recording, Capture card. A big rearchitecture would be needed to achieve this and still then it's unclear to me how the user would control the elements in realtime.

To adjust the content on screen while the stream is running, one would have to reprogram the React app? Seems questionable to me.

However, you can use @remotion/player and update the content live, and embed that over OBS for example! https://www.remotion.dev/docs/player/ So in a way, it's already possible.

Nonetheless, still thanks a lot for bringing up the idea and hope you can understand this decision!

**Comment by artdevgame** [comment]
@JonnyBurger I'm looking to achieve something similar.

To answer this:
> unclear to me how the user would control the elements in realtime

I would like to control positioning of elements (GIFs, etc) programmatically & their appearance (delay/duration) would be toggled using pubsub/socket events.

**Comment by JonnyBurger** [comment]
@artdevgame I think the best way to do that is to create a website and add the browser source to OBS. Control everything using websockets etc, I think that is a really cool idea but completely separate from what we are doing at the moment 😊
