### ISSUE TITLE
LICENSE change?

### ISSUE THREAD

**Issue by nicopace** [JonnyBurger/remotion#27]
Do you plan to turn it into an open source project?
GPL or LGPL or AGPL would be ok.
Thanks!

**Comment by nicopace** [comment]
There is a similar GPL3 project that might be interesting to use if you can't use the license of remotion, or if remotion wants to integrate with them: https://github.com/pankod/canvas2video

**Comment by JonnyBurger** [comment]
I have carefully picked the license model I have right now, I don't see a reason to switch.

The problem with making it a completely free license would be that it would be a big burden for me to maintain the library, without me getting anything in return (I don't think OSS sponsorship models work very well). I don't wanna go down this path.

**Comment by nicopace** [comment]
Well... because the model you've picked might not be compatible with the FLOSS nature.
People might not contribute to the project if they don't know it is community owned.

On the other hand, as the project has some potential, your project could grow into a community developed project (like canvas2video) and get contributions all over the world.

Many FLOSS projects are very healthy (many I am part of, like manyver.se for example).... and helathy doesn't necessary mean that it gives you a passive income, but that is alive and kicking!

As the project is very interesting, people might hire you to integrate your software with theirs, or do bounties for implementing certain features.

I mean... it is fine you do what you want with your time and what it comes out of it, I just felt that it was a pitty that it had that license, as it is incompatible with so many others.

Thanks for your time.

**Comment by jezell** [comment]
License choice is unfortunate for something that wouldn't exist without FFMPEG doing the heavy lifting.

**Comment by JonnyBurger** [comment]
To be clear I don't want it to be compatible with the FLOSS nature.

I did foresee this library becoming a maintenance burden and I've been working on it full-time since launch. So I am very glad that I did this license, otherwise there would be no perspective for me other than a lot of free work for other people (who in turn may make a profit out of it - remember I only charge big companies).

I am in my twenties and don't already have accumulated such a big wealth that I can just spend so much time to build software and give it away without any restriction.

Sure the software is built upon OSS, but so are many billion dollar companies and nobody seems to have a problem with it that they don't release their code for free. I'm planning to make a blog post or video in the future about why I chose this license, until then I'm not going to elaborate on it further.

**Comment by mifi** [comment]
Maybe there could be a "Similar projects" section in the readme listing open source alternatives for people looking for that? I have a similar open source project [editly](https://github.com/mifi/editly), I will definitely put remotion in my "See also" section.

**Comment by JonnyBurger** [comment]
Thanks a lot @mifi for including Remotion on your "See also" list! I'm also for the idea of having one for Remotion.
I like a lot how @react-navigation is doing it, making a page about alternatives in their docs: https://reactnavigation.org/docs/alternatives/

They even have an anti-pitch telling what the weaknesses are of their library: https://reactnavigation.org/docs/pitch

If we make such a page, we can also include https://github.com/ysulyma/ractive-player by @ysulyma.
