### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by dqbd** [JonnyBurger/remotion#39]
Hey! 👋  Having issues running `yarn create video` on M1 powered device w/out Rosetta 2.

![image](https://user-images.githubusercontent.com/1443449/107457575-9b2f7100-6b52-11eb-9e82-ed921357097b.png)

Node v15.6.0 (native ARM), npm 7.4.0, yarn 1.x

It seems like the issue is related to https://github.com/puppeteer/puppeteer/issues/6622, as Puppeteer does not find the proper installed binary during npm (re)build nor during launching browser

**Comment by dqbd** [comment]
It seems like the issue is not yet resolved as of `puppeteer@^7.0.4`, cannot install and launch Chromium without specifying `executablePath` in `packages/renderer`

**Comment by JonnyBurger** [comment]
Thanks for reporting! In that case, we must provide the option to specify an executable yourself. I just noticed that there is an `puppeteer-core` package which doesn't install the browser on installation. Would also be good because Puppeteer is not required for the preview, so the installation will be much faster.

Plus so many people already have Chrome installed!
Will tackle this soon.

**Comment by jcblw** [comment]
I got this project working on  Mac M1. You just need to disable the auto-download of Chromium and install it manually. 

I have this in my `~/.zshrc` since I run a few projects that use puppeteer.

```shell
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
# Path for chromium needed for puppeteer
export PUPPETEER_EXECUTABLE_PATH="/Users/<username>/<path-may-vary>/Chromium.app/Contents/MacOS/Chromium"
```

Got this info from puppeteers issues. More info here.
https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-749069120

**Comment by c0bra** [comment]
Note for others that I was getting an error like this: "Chromium.app is damaged. You should move it to Trash."

And had to reinstall chromium unquarantined: `brew reinstall chromium --no-quarantine`

Not sure if that's the ideal solution, but it worked.
