### ISSUE TITLE
Use humpf as a spring engine

### ISSUE THREAD

**Issue by etienne-dldc** [JonnyBurger/remotion#64]
Hi 👋 

I'm the author of [Humpf](https://humpf.etienne.tech/), a spring library and I think this project could benefit from using it instead or alongside of the current `spring()` function.
The main advantage of `humpf` compared to the current `spring()` is that `humpf` is time based and does not need to compute every past values to get the current one. This also mean that the framerate does not matter (as long as you get the current time).

Another advantage of `humpf` is that it handle velocity, both as input and output which allow to chain spring motion without a sudden change of velocity.

**Comment by JonnyBurger** [comment]
Hi Etienne!

Thanks a lot for the idea, Humpf looks a lot more advanced, thank you for making this project!
What I find cool is that you can change the direction of the animation and it will look natural because you seem to take the velocity of the previous animation into account, something I am not quite understanding conceptually but want to learn.

If we want to replace the current spring function with Humpf, we need to make sure that people can upgrade and use the same API and don't have their animations behave differently. I imagine this type of backwards compatibility is pretty hard to, so I am a bit skeptical, but maybe you can convince me otherwise.

If backwards-compatibility is too constraining, I would love to see an advanced spring function outside of core. The current spring function can be fully implemented with APIs exposed by Remotion, so this would surely work. Improving the spring function is for the moment not a priority for me though as there are bugs and missing features to work on. So I would personally not soon work on it, but if somebody is willing to pick it up, gladyl!

**Comment by JonnyBurger** [comment]
I am closing this because it doesn't seem likely there will be more activity on this in the near future.
If someone is motivated to work on improving the spring function, let me know and we can coordinate!
